title: Design Analytics
description: Design Analytics Course
# theme: just-the-docs
remote_theme: pmarsceill/just-the-docs

url: https://design-analytics.github.io

# aux_links:
#   Template Repository: https://github.com/just-the-docs/just-the-docs-template
